[workspace]
    members=["crates/rivet-cli", "crates/rivet-core", "crates/rivet-package", "crates/rivet-repository", "crates/rivet-resolver", "crates/rivet-tui"]

    resolver="3"

    [workspace.package]
        authors=["Frank1o3"]
        edition="2024"
        license="BSD-3-Clause"
        repository="https://github.com/Frank1o3/rivet.git"
        version="0.1.8"

    [workspace.dependencies]
        rivet-cli={path="crates/rivet-cli"}
        rivet-core={path="crates/rivet-core"}
        rivet-package={path="crates/rivet-package"}
        rivet-repository={path="crates/rivet-repository"}
        rivet-resolver={path="crates/rivet-resolver"}

        bzip2="0.6"
        flate2="1.1.9"
        reqwest={version="0.13.4", features=["blocking", "brotli", "deflate", "gzip", "rustls", "zstd"]}
        tar="0.4.46"
        xz2="0.1.7"
        zip="8.6.0"

        anyhow="1.0"
        thiserror="2.0"

        serde={version="1.0", features=["derive"]}
        serde_json="1.0"

        hex="0.4.3"
        semver={version="1.0", features=["serde"]}
        sha2="0.11.0"

        dirs="6.0.0"
        libc="0.2.189"
        tempfile="3.17"
        walkdir="2.5"
