[package]
    authors.workspace=true
    edition.workspace=true
    license.workspace=true
    name="rivet-package"
    repository.workspace=true
    version.workspace=true

[dependencies]
    bzip2.workspace=true
    dirs.workspace=true
    flate2.workspace=true
    mlua.workspace=true
    reqwest.workspace=true
    rivet-core.workspace=true
    serde.workspace=true
    tar.workspace=true
    tempfile.workspace=true
    thiserror.workspace=true
    walkdir.workspace=true
    xz2.workspace=true
    zip.workspace=true

[dev-dependencies]
    serde_json.workspace=true
